aplicacion:
  nombre: Tutorial Spring Boot
   
server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexos
    username: expert_prod
    password: expert_prod
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      
logging:
  level:
    org:
      hibernate:
        SQL: debug